site_name: My Portfolio

theme:
  name: material
  palette:
    primary: blue
    accent: cyan
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - content.tabs.link
    - content.action.edit

extra_css:
  - assets/styles.css

extra_javascript:
  - assets/profile-inject.js 

nav:
  - Home: index.md
  - About Me:
      - Overview: about/index.md
      - Skills: about/skills.md
      - Experience: about/experience.md
      - Hobbies: about/hobbies.md
  - Projects: projects.md
  - Contact: contact.md

